apiVersion: apps/v1
kind: Deployment
metadata:
  name: imgproxy
  labels:
    app: imgproxy
spec:
  selector:
    matchLabels:
      app: imgproxy
  replicas: 3
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: imgproxy
    spec:
      containers:
      - name: imgproxy
        image: darthsim/imgproxy:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 0.5
          requests:
            cpu: 0.2
