apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: imgproxy-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: imgproxy
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50
