name: TechTest Account Deployment Pipeline
run-name: TechTest Account Deployment ${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      container_image_tf:
        required: true
        type: string
      deployEnvironment:
        required: true
        type: string
      terraformAction:
        default: apply
        type: string
  workflow_dispatch:
    inputs:
      container_image_tf:
        required: true
        type: string
        default: "322411843910.dkr.ecr.eu-west-2.amazonaws.com/techtest-prd-account-terraform:latest"
      deployEnvironment:
        description: Name of the environment to deploy
        required: true
        default: default
        type: string
      terraformAction:
        description: Apply or Destroy
        required: true
        default: apply
        type: choice
        options:
          - apply
          - destroy

concurrency:
  group: acct-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}-${{ github.event.inputs.deployEnvironment }}
  cancel-in-progress: false

defaults:
  run:
    shell: bash

env:
  PROJECT_NAME: techtest
  COMPONENT: account

jobs:
  terraform_deploy:
    name: Terraform Deploy
    runs-on:
      - self-hosted
      - techtest
    container: ${{ inputs.container_image_tf }}
    environment: ${{ inputs.deployEnvironment }}
    outputs:
      new_environment: ${{ steps.terraform.outputs.new_environment }}
      environment: ${{ steps.export_terraform.outputs.environment }}
    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3
      - name: Terraform Apply or Destroy
        id: terraform
        run: |-
          echo "${{ inputs.terraformAction }}ing environment ${{ inputs.deployEnvironment }} for ${COMPONENT}"
          cd "${COMPONENT}/terraform"
          terraform init --upgrade
          ../../deploy/initialise_workspace.sh ${{ inputs.deployEnvironment }}
          terraform ${{ inputs.terraformAction }} --auto-approve
      - name: Export Terraform Outputs
        id: export_terraform
        if: ${{ inputs.terraformAction == 'apply' }}
        run: |-
          cd "${COMPONENT}/terraform"
          ../../deploy/export_terraform_outputs.sh
